# Laptop Host - GNOME Configuration
# dconf settings (host-specific overrides only)
# Extension installation AND activation are handled by modules/desktop/gnome/extensions.nix
# Configure which extensions via modules.desktop.gnome.extensions.* in configuration.nix
{lib, ...}: {
  # Laptop-specific dconf settings (power savings)
  programs.dconf.profiles.user.databases = [
    {
      lockAll = false;
      settings = {
        # Shell - favorites only (enabled-extensions auto-generated by extensions.nix)
        "org/gnome/shell" = {
          favorite-apps = [
            "org.gnome.Nautilus.desktop"
            "firefox.desktop"
            "org.gnome.Terminal.desktop"
            "code.desktop"
          ];
        };

        # Mutter - desktop features
        "org/gnome/mutter" = {
          edge-tiling = true;
          dynamic-workspaces = true;
          workspaces-only-on-primary = true;
          center-new-windows = true;
          experimental-features = [
            "scale-monitor-framebuffer"
          ];
        };

        # Session - laptop idle (5 min)
        "org/gnome/desktop/session" = {
          idle-delay = lib.gvariant.mkUint32 300;
        };

        # Power - laptop optimized
        "org/gnome/settings-daemon/plugins/power" = {
          sleep-inactive-ac-type = "suspend";
          sleep-inactive-battery-type = "suspend";
          power-button-action = "suspend";
          idle-dim = false;
          ambient-enabled = false;
        };
      };
    }
  ];
}
