# Desktop Host - GNOME Configuration
# dconf settings (host-specific overrides only)
# Extension installation AND activation are handled by modules/desktop/gnome/extensions.nix
# Configure which extensions via modules.desktop.gnome.extensions.* in configuration.nix
{lib, ...}: {
  # Desktop-specific dconf settings (AMD GPU optimizations, power)
  programs.dconf.profiles.user.databases = [
    {
      lockAll = false;
      settings = {
        # Shell - favorites only (enabled-extensions auto-generated by extensions.nix)
        "org/gnome/shell" = {
          favorite-apps = [
            "org.gnome.Nautilus.desktop"
            "firefox.desktop"
            "org.gnome.Terminal.desktop"
            "kitty.desktop"
            "code.desktop"
            "steam.desktop"
          ];
        };

        # Mutter - AMD GPU optimizations
        "org/gnome/mutter" = {
          edge-tiling = true;
          dynamic-workspaces = true;
          workspaces-only-on-primary = false;
          center-new-windows = true;
          experimental-features = ["scale-monitor-framebuffer" "rt-scheduler"];
          dynamic-triple-buffering = true;
          force-sync = false;
        };

        # Session - desktop idle (15 min)
        "org/gnome/desktop/session" = {
          idle-delay = lib.gvariant.mkUint32 900;
        };

        # Power - desktop (always plugged in)
        "org/gnome/settings-daemon/plugins/power" = {
          sleep-inactive-ac-type = "nothing";
          sleep-inactive-battery-type = "suspend";
          power-button-action = "interactive";
        };
      };
    }
  ];

  # AMD GPU environment variables
  environment.sessionVariables = {
    "LIBVA_DRIVER_NAME" = "radeonsi";
    "VDPAU_DRIVER" = "radeonsi";
  };
}
