# Desktop Host - GNOME Configuration
# dconf settings (host-specific overrides only)
# Extension installation AND activation are handled by modules/desktop/gnome/extensions.nix
# Configure which extensions via modules.desktop.gnome.extensions.* in configuration.nix
{lib, pkgs, ...}: {
  # Desktop-specific dconf settings (AMD GPU optimizations, power)
  programs.dconf.profiles.user.databases = [
    {
      lockAll = false;
      settings = {
        # Shell - favorites only (enabled-extensions auto-generated by extensions.nix)
        "org/gnome/shell" = {
          favorite-apps = [
            "org.gnome.Nautilus.desktop"
            "firefox.desktop"
            "org.gnome.Terminal.desktop"
            "kitty.desktop"
            "code.desktop"
            "steam.desktop"
          ];
        };

        # Mutter - AMD GPU optimizations
        "org/gnome/mutter" = {
          edge-tiling = true;
          dynamic-workspaces = true;
          workspaces-only-on-primary = false;
          center-new-windows = true;
          experimental-features = ["scale-monitor-framebuffer" "rt-scheduler"];
          dynamic-triple-buffering = true;
          force-sync = false;
        };

        # Session - screen dims after 5 min idle
        "org/gnome/desktop/session" = {
          idle-delay = lib.gvariant.mkUint32 300;
        };

        # Screensaver - lock and blank screen after idle
        "org/gnome/desktop/screensaver" = {
          lock-enabled = true;
          lock-delay = lib.gvariant.mkUint32 30; # Lock 30s after screen blanks
          idle-activation-enabled = true;
        };

        # Power - suspend after 30 min idle on AC (Caffeine overrides when gaming)
        "org/gnome/settings-daemon/plugins/power" = {
          sleep-inactive-ac-type = "suspend";
          sleep-inactive-ac-timeout = lib.gvariant.mkInt32 1800; # 30 min
          power-button-action = "interactive";
        };
      };
    }
  ];

  # AMD GPU environment variables
  environment.sessionVariables = {
    "LIBVA_DRIVER_NAME" = "radeonsi";
    "VDPAU_DRIVER" = "radeonsi";
  };

  # Askpass for GUI sudo prompts (used by nh, Claude Code, etc.)
  programs.ssh.askPassword = "${pkgs.ssh-askpass-fullscreen}/bin/ssh-askpass-fullscreen";
  environment.variables = {
    "SUDO_ASKPASS" = "${pkgs.ssh-askpass-fullscreen}/bin/ssh-askpass-fullscreen";
  };
}
