# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Bootloader.
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/nvme0n1";
  boot.loader.grub.useOSProber = false;

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/66429e28-aff7-4427-a85e-5f742179ae25";
    fsType = "ext4";
  };

  swapDevices = [];

  # zramSwap configuration added by user:
  # Enables compressed RAM swap using zram-generator under the hood.
  zramSwap.enable = true;
  # Limit total uncompressed memory in zram to 25% (≈16 GiB of 64 GiB)
  zramSwap.memoryPercent = 25;
  # Use high-ratio, fast ZSTD (kernel ≥5.5)
  zramSwap.algorithm = "zstd";
  # Ensure zram is preferred over disk swap
  zramSwap.priority = 10;
  # Number of zram devices (default 1)
  zramSwap.swapDevices = 1;

  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp9s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
