keys:
  # Personal admin key (for editing secrets locally)
  - &admin_key age1fja8p7p5axgw0087n8qzqn7awgyjnuukggs3y6a06nhm9jsyg9eqxpkhn3

  # Laptop host key (from ssh-to-age output)
  - &host_laptop age163xpl969k5mm57ffehqnhjvdf3kh8zjq7eltt8adknaqrqappyus74vrhl

creation_rules:
  # Laptop host secrets
  - path_regex: (laptop|secrets/laptop)\.yaml$
    key_groups:
      - age:
          - *admin_key
          - *host_laptop
